version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - 9379:6379  
  core:
    build:      
      context: .      
      dockerfile: ./docker/core/Dockerfile
    depends_on:
      - 'postgres'
      - 'redis'
    volumes:
      - '.:/var/www/done-core'
    env_file:
      - '.env'

  # worker:
    # build:
    #   context: .
    #   dockerfile: ./docker/api/Dockerfile
    # depends_on:
    #   - 'postgres'
    #   - 'redis'
    # command: sidekiq -c 2 -v -q default -q mailer -q priority
    # volumes:
    #   - '.:/var/www/hbt-api'
    # env_file:
    #   - '.env'
    # environment:
    #   - REDIS_URL=redis://redis:6379/0
  # web: 
  #   build:      
  #     context: .      
  #     dockerfile: ./docker/web/Dockerfile    
  #   depends_on:      
  #     - core    
  #   ports:      
  #     - 80:80
    
volumes:
  redis:
  postgres:

